'use client';
// ─── ModuleContentRenderer ────────────────────────────────────────────────────
// Smart renderer that turns AI-generated markdown into beautiful visual cards.
// Handles the specific patterns generated by PDI modules 3, 4, and 5.

import React from 'react';

// ── Utility: strip markdown symbols from a string ──────────────────────────────
function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\*\*\*(.+?)\*\*\*/g, '$1')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1');
}

// ── Utility: render inline markdown to JSX-safe HTML string ───────────────────
function inlineMd(text: string): string {
  return text
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong style="color:#e2d8f5;font-weight:700">$1</strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:var(--text-primary);font-weight:700">$1</strong>')
    .replace(/`([^`]+)`/g, '<code style="background:rgba(255,255,255,0.08);padding:2px 6px;border-radius:4px;font-size:11px;font-family:monospace;color:#a78bfa">$1</code>')
    .replace(/↗/g, '<span style="color:#ef4444">↗</span>')
    .replace(/↘/g, '<span style="color:#22c55e">↘</span>')
    .replace(/↔/g, '<span style="color:#94a3b8">↔</span>')
    .replace(/⇿/g, '<span style="color:#f59e0b">⇿</span>')
    .replace(/🔴/g, '<span style="color:#ef4444">🔴</span>')
    .replace(/🟡/g, '<span style="color:#f59e0b">🟡</span>')
    .replace(/🟢/g, '<span style="color:#22c55e">🟢</span>')
    .replace(/✅/g, '<span style="color:#22c55e">✅</span>')
    .replace(/⚠️/g, '<span style="color:#f59e0b">⚠️</span>');
}

// ── Types ─────────────────────────────────────────────────────────────────────
type Block =
  | { type: 'h1'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'h4'; text: string }
  | { type: 'hr' }
  | { type: 'blockquote'; text: string }
  | { type: 'labeled'; label: string; body: string }  // * **Label**: text
  | { type: 'action'; label: string; body: string }   // - **Label**: text (Acción/Urgencia/Justificación)
  | { type: 'bullet'; text: string }                  // - plain bullet
  | { type: 'numbered'; num: string; text: string }   // 1. text
  | { type: 'paragraph'; text: string }
  | { type: 'table'; header: string[]; rows: string[][] };

// ── Parser: text → Block[] ─────────────────────────────────────────────────────
function parseBlocks(text: string): Block[] {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const blocks: Block[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    // Empty line
    if (!trimmed) { i++; continue; }

    // H1
    if (/^# /.test(trimmed)) {
      blocks.push({ type: 'h1', text: trimmed.slice(2).trim() });
      i++; continue;
    }
    // H2
    if (/^## /.test(trimmed)) {
      blocks.push({ type: 'h2', text: trimmed.slice(3).trim() });
      i++; continue;
    }
    // H3
    if (/^### /.test(trimmed)) {
      blocks.push({ type: 'h3', text: trimmed.slice(4).trim() });
      i++; continue;
    }
    // H4
    if (/^#### /.test(trimmed)) {
      blocks.push({ type: 'h4', text: trimmed.slice(5).trim() });
      i++; continue;
    }
    // HR
    if (/^---+$/.test(trimmed)) {
      blocks.push({ type: 'hr' });
      i++; continue;
    }
    // Blockquote
    if (/^> /.test(trimmed)) {
      const bqLines = [trimmed.slice(2)];
      i++;
      while (i < lines.length && /^> /.test(lines[i].trim())) {
        bqLines.push(lines[i].trim().slice(2));
        i++;
      }
      blocks.push({ type: 'blockquote', text: bqLines.join(' ') });
      continue;
    }
    // Table
    if (/^\|/.test(trimmed)) {
      const tableLines = [trimmed];
      i++;
      while (i < lines.length && /^\|/.test(lines[i].trim())) {
        tableLines.push(lines[i].trim());
        i++;
      }
      if (tableLines.length >= 3) {
        const parseRow = (r: string) => r.slice(1, -1).split('|').map(c => c.trim());
        const header = parseRow(tableLines[0]);
        const rows = tableLines.slice(2).filter(r => !/^\|[-:| ]+\|$/.test(r)).map(parseRow);
        blocks.push({ type: 'table', header, rows });
      }
      continue;
    }
    // Labeled bullet: * **Label**: body  OR  * **Label** body
    const labeledMatch = trimmed.match(/^\* (\*\*[^*]+\*\*):?\s*(.*)/);
    if (labeledMatch) {
      const rawLabel = labeledMatch[1].replace(/\*\*/g, '');
      const body = labeledMatch[2] || '';
      blocks.push({ type: 'labeled', label: rawLabel, body });
      i++; continue;
    }
    // Action bullet: - **Label**: body (for Acción, Urgencia, Justificación, etc.)
    const actionMatch = trimmed.match(/^- (\*\*[^*]+\*\*):?\s*(.*)/);
    if (actionMatch) {
      const rawLabel = actionMatch[1].replace(/\*\*/g, '');
      const body = actionMatch[2] || '';
      blocks.push({ type: 'action', label: rawLabel, body });
      i++; continue;
    }
    // Plain bullet: - text
    if (/^- /.test(trimmed)) {
      blocks.push({ type: 'bullet', text: trimmed.slice(2) });
      i++; continue;
    }
    // Plain asterisk bullet: * text (not bold)
    if (/^\* [^*]/.test(trimmed) || trimmed === '* ') {
      blocks.push({ type: 'bullet', text: trimmed.slice(2) });
      i++; continue;
    }
    // Numbered list
    const numMatch = trimmed.match(/^(\d+)\. (.*)/);
    if (numMatch) {
      blocks.push({ type: 'numbered', num: numMatch[1], text: numMatch[2] });
      i++; continue;
    }
    // Paragraph (collect continuation lines)
    const paraLines = [trimmed];
    i++;
    while (
      i < lines.length &&
      lines[i].trim() &&
      !/^(#|>|---|\*\*|##|###|\||-)/.test(lines[i].trim()) &&
      !/^\* \*\*/.test(lines[i].trim()) &&
      !/^- \*\*/.test(lines[i].trim()) &&
      !/^\d+\./.test(lines[i].trim())
    ) {
      paraLines.push(lines[i].trim());
      i++;
    }
    blocks.push({ type: 'paragraph', text: paraLines.join(' ') });
  }

  return blocks;
}

// ── Helpers for grouping ───────────────────────────────────────────────────────
function groupConsecutive<T extends Block>(
  blocks: Block[],
  predicate: (b: Block) => b is T
): Array<Block | T[]> {
  const result: Array<Block | T[]> = [];
  let group: T[] = [];
  for (const b of blocks) {
    if (predicate(b)) {
      group.push(b);
    } else {
      if (group.length) { result.push(group); group = []; }
      result.push(b);
    }
  }
  if (group.length) result.push(group);
  return result;
}

// ── Label to color mapping ────────────────────────────────────────────────────
const ACTION_LABEL_STYLES: Record<string, { bg: string; border: string; color: string; icon: string }> = {
  'acción':         { bg: 'rgba(59,130,246,0.08)', border: 'rgba(59,130,246,0.25)', color: '#60a5fa', icon: '⚡' },
  'accion':         { bg: 'rgba(59,130,246,0.08)', border: 'rgba(59,130,246,0.25)', color: '#60a5fa', icon: '⚡' },
  'urgencia':       { bg: 'rgba(239,68,68,0.07)', border: 'rgba(239,68,68,0.25)', color: '#f87171', icon: '🚨' },
  'justificación':  { bg: 'rgba(212,175,55,0.07)', border: 'rgba(212,175,55,0.25)', color: '#d4af37', icon: '📋' },
  'justificacion':  { bg: 'rgba(212,175,55,0.07)', border: 'rgba(212,175,55,0.25)', color: '#d4af37', icon: '📋' },
  'evidencia':      { bg: 'rgba(139,92,246,0.07)', border: 'rgba(139,92,246,0.25)', color: '#a78bfa', icon: '🔬' },
  'evolución temporal': { bg: 'rgba(34,197,94,0.07)', border: 'rgba(34,197,94,0.2)', color: '#4ade80', icon: '📈' },
  'evolucion temporal': { bg: 'rgba(34,197,94,0.07)', border: 'rgba(34,197,94,0.2)', color: '#4ade80', icon: '📈' },
  'correlación clínica': { bg: 'rgba(16,185,129,0.07)', border: 'rgba(16,185,129,0.2)', color: '#34d399', icon: '🔗' },
  'correlacion clinica': { bg: 'rgba(16,185,129,0.07)', border: 'rgba(16,185,129,0.2)', color: '#34d399', icon: '🔗' },
  'probabilidad estimada': { bg: 'rgba(249,115,22,0.07)', border: 'rgba(249,115,22,0.2)', color: '#fb923c', icon: '📊' },
  'nivel de preocupación': { bg: 'rgba(239,68,68,0.07)', border: 'rgba(239,68,68,0.2)', color: '#f87171', icon: '⚠️' },
  'nivel de preocupacion': { bg: 'rgba(239,68,68,0.07)', border: 'rgba(239,68,68,0.2)', color: '#f87171', icon: '⚠️' },
};

function getLabelStyle(label: string) {
  const key = label.toLowerCase().trim();
  return ACTION_LABEL_STYLES[key] ?? {
    bg: 'rgba(255,255,255,0.03)',
    border: 'rgba(255,255,255,0.1)',
    color: 'var(--text-secondary)',
    icon: '›',
  };
}

// ── Sub-renderers ─────────────────────────────────────────────────────────────

function RenderTable({ header, rows }: { header: string[]; rows: string[][] }) {
  return (
    <div style={{ overflowX: 'auto', margin: '16px 0', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.07)' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead style={{ background: 'rgba(212,175,55,0.06)' }}>
          <tr>
            {header.map((h, i) => (
              <th key={i} style={{ padding: '10px 16px', textAlign: 'left', fontSize: '11px', fontWeight: 700, color: 'var(--gold-primary)', borderBottom: '1px solid rgba(212,175,55,0.2)', whiteSpace: 'nowrap', letterSpacing: '0.04em' }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, ri) => (
            <tr key={ri} style={{ background: ri % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.015)', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
              {row.map((cell, ci) => (
                <td key={ci} style={{ padding: '9px 16px', fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.6 }}
                  dangerouslySetInnerHTML={{ __html: inlineMd(cell) }} />
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function RenderBlockquote({ text }: { text: string }) {
  return (
    <div style={{ margin: '16px 0', padding: '14px 20px', borderLeft: '3px solid var(--gold-primary)', background: 'rgba(212,175,55,0.06)', borderRadius: '0 10px 10px 0', fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.75, fontStyle: 'italic' }}
      dangerouslySetInnerHTML={{ __html: inlineMd(text) }} />
  );
}

function RenderH2({ text }: { text: string }) {
  return (
    <h2 style={{ fontSize: '17px', fontWeight: 800, margin: '32px 0 16px', color: 'var(--text-primary)', paddingBottom: '10px', borderBottom: '1px solid rgba(255,255,255,0.08)', letterSpacing: '-0.01em', display: 'flex', alignItems: 'center', gap: '10px' }}
      dangerouslySetInnerHTML={{ __html: inlineMd(text) }} />
  );
}

function RenderH3({ text }: { text: string }) {
  // System headers — render as a beautiful colored card header
  return (
    <div style={{ margin: '24px 0 12px', padding: '12px 18px', background: 'linear-gradient(135deg, rgba(212,175,55,0.08) 0%, rgba(212,175,55,0.03) 100%)', border: '1px solid rgba(212,175,55,0.2)', borderRadius: '10px', display: 'flex', alignItems: 'center', gap: '10px' }}>
      <div style={{ width: '4px', height: '28px', background: 'var(--gold-primary)', borderRadius: '2px', flexShrink: 0 }} />
      <span style={{ fontSize: '15px', fontWeight: 700, color: 'var(--gold-primary)', lineHeight: 1.3 }}
        dangerouslySetInnerHTML={{ __html: inlineMd(text) }} />
    </div>
  );
}

function RenderH4({ text }: { text: string }) {
  return (
    <h4 style={{ fontSize: '12px', fontWeight: 700, margin: '20px 0 8px', color: 'rgba(212,175,55,0.8)', textTransform: 'uppercase', letterSpacing: '0.08em' }}
      dangerouslySetInnerHTML={{ __html: inlineMd(text) }} />
  );
}

function RenderLabeledItem({ label, body }: { label: string; body: string }) {
  const style = getLabelStyle(label);
  return (
    <div style={{ margin: '6px 0', padding: '10px 14px', background: style.bg, border: `1px solid ${style.border}`, borderRadius: '8px', display: 'flex', gap: '10px', alignItems: 'flex-start' }}>
      <span style={{ fontSize: '12px', flexShrink: 0, marginTop: '2px' }}>{style.icon}</span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <span style={{ fontSize: '11px', fontWeight: 700, color: style.color, textTransform: 'uppercase', letterSpacing: '0.06em', marginRight: '8px' }}>{label}:</span>
        <span style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.75 }}
          dangerouslySetInnerHTML={{ __html: inlineMd(body) }} />
      </div>
    </div>
  );
}

function RenderActionItem({ label, body }: { label: string; body: string }) {
  const style = getLabelStyle(label);
  return (
    <div style={{ margin: '5px 0', padding: '9px 14px', background: style.bg, border: `1px solid ${style.border}`, borderRadius: '8px', display: 'flex', gap: '10px', alignItems: 'flex-start' }}>
      <span style={{ fontSize: '13px', flexShrink: 0, marginTop: '1px' }}>{style.icon}</span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <span style={{ fontSize: '11px', fontWeight: 700, color: style.color, textTransform: 'uppercase', letterSpacing: '0.06em', marginRight: '8px' }}>{label}:</span>
        <span style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.75 }}
          dangerouslySetInnerHTML={{ __html: inlineMd(body) }} />
      </div>
    </div>
  );
}

function RenderBullets({ bullets }: { bullets: Extract<Block, { type: 'bullet' }>[] }) {
  return (
    <ul style={{ margin: '8px 0 14px', padding: '0 0 0 6px', borderLeft: '2px solid rgba(212,175,55,0.2)', listStyle: 'none' }}>
      {bullets.map((b, i) => (
        <li key={i} style={{ padding: '6px 0', display: 'flex', gap: '10px', alignItems: 'flex-start', lineHeight: 1.75 }}>
          <span style={{ color: 'var(--gold-primary)', flexShrink: 0, fontSize: '9px', marginTop: '6px' }}>●</span>
          <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}
            dangerouslySetInnerHTML={{ __html: inlineMd(b.text) }} />
        </li>
      ))}
    </ul>
  );
}

function RenderNumbered({ items }: { items: Extract<Block, { type: 'numbered' }>[] }) {
  return (
    <ol style={{ margin: '8px 0 14px', padding: '0 0 0 6px', listStyle: 'none', borderLeft: '2px solid rgba(212,175,55,0.15)' }}>
      {items.map((b, i) => (
        <li key={i} style={{ padding: '6px 0', display: 'flex', gap: '12px', alignItems: 'flex-start', lineHeight: 1.75 }}>
          <span style={{ color: 'var(--gold-primary)', fontWeight: 700, fontSize: '12px', minWidth: '22px', flexShrink: 0, marginTop: '2px' }}>{b.num}.</span>
          <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}
            dangerouslySetInnerHTML={{ __html: inlineMd(b.text) }} />
        </li>
      ))}
    </ol>
  );
}

function RenderParagraph({ text }: { text: string }) {
  return (
    <p style={{ margin: '0 0 14px', lineHeight: 1.85, color: 'var(--text-secondary)', fontSize: '14px' }}
      dangerouslySetInnerHTML={{ __html: inlineMd(text) }} />
  );
}

// ── Main component ─────────────────────────────────────────────────────────────
export default function ModuleContentRenderer({ content }: { content: string }) {
  const blocks = parseBlocks(content);

  // Group consecutive bullets/numbered items
  const groupedBlocks: Array<Block | Block[]> = [];
  let i = 0;
  while (i < blocks.length) {
    const b = blocks[i];
    if (b.type === 'bullet') {
      const group: Extract<Block, { type: 'bullet' }>[] = [];
      while (i < blocks.length && blocks[i].type === 'bullet') {
        group.push(blocks[i] as Extract<Block, { type: 'bullet' }>);
        i++;
      }
      groupedBlocks.push(group);
    } else if (b.type === 'numbered') {
      const group: Extract<Block, { type: 'numbered' }>[] = [];
      while (i < blocks.length && blocks[i].type === 'numbered') {
        group.push(blocks[i] as Extract<Block, { type: 'numbered' }>);
        i++;
      }
      groupedBlocks.push(group);
    } else {
      groupedBlocks.push(b);
      i++;
    }
  }

  return (
    <div style={{ fontFamily: 'var(--font-main)' }}>
      {groupedBlocks.map((item, idx) => {
        // Group of bullets
        if (Array.isArray(item)) {
          if (item.length === 0) return null;
          if (item[0].type === 'bullet') {
            return <RenderBullets key={idx} bullets={item as Extract<Block, { type: 'bullet' }>[]} />;
          }
          if (item[0].type === 'numbered') {
            return <RenderNumbered key={idx} items={item as Extract<Block, { type: 'numbered' }>[]} />;
          }
          return null;
        }

        const b = item as Block;
        switch (b.type) {
          case 'h1': return null; // h1 is the module title, not shown in body
          case 'h2': return <RenderH2 key={idx} text={b.text} />;
          case 'h3': return <RenderH3 key={idx} text={b.text} />;
          case 'h4': return <RenderH4 key={idx} text={b.text} />;
          case 'hr': return <hr key={idx} style={{ border: 'none', borderTop: '1px solid rgba(255,255,255,0.07)', margin: '24px 0' }} />;
          case 'blockquote': return <RenderBlockquote key={idx} text={b.text} />;
          case 'table': return <RenderTable key={idx} header={b.header} rows={b.rows} />;
          case 'labeled': return <RenderLabeledItem key={idx} label={b.label} body={b.body} />;
          case 'action': return <RenderActionItem key={idx} label={b.label} body={b.body} />;
          case 'paragraph': return <RenderParagraph key={idx} text={b.text} />;
          default: return null;
        }
      })}
    </div>
  );
}
